### https://jellyfin.org/docs/general/installation/container/
### https://jellyfin.org/docs/general/networking/#port-bindings

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:10.9.1
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - type: bind
        source: /media
        target: /media
    environment: ### Optional - alternative address used for autodiscovery
      - JELLYFIN_PublishedServerUrl=http://jellyfin.greyman.space
    user: 1001:1001
    restart: unless-stopped
    ports:
    - 8096:8096/tcp ### HTTP
    - 8920:8920/tcp ### HTTPS
    - 1900:1900/udp ### Service Discovery
    - 7359:7359/udp ### Client Discovery

volumes:
  jellyfin_config:
  jellyfin_cache:
