services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:10.9.1
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - type: bind
        source: /media
        target: /media
    environment: ### Optional - alternative address used for autodiscovery
      - JELLYFIN_PublishedServerUrl=http://jellyfin.greyman.space
    user: 1001:1001
    restart: unless-stopped
    ports:
    - 8096:8096

volumes:
  jellyfin-config:
  jellyfin-cache:
